### PR TITLE
Log Review

### PR DESCRIPTION
**Pull request by Romanitho**
# Proposed Changes

- Review log management
- Added log on WAU installation

### CODE REVIEW

**Comment by Romanitho** [comment]
@KnifMelti is that ok with your work? 😇

**Comment by KnifMelti** [comment]
You said tomorrow 😍

**Comment by Romanitho** [comment]
yes, but I want it in the nightly built of tonight ^^

**Comment by Romanitho** [comment]
seams OK so far on my side. I merge, will see tomorrow for troubleshoot in case something is broken

**Comment by Romanitho** [comment]
if everything is good, I'll work on ServiceUI. I have a plan to onboard it with Github Actions. This way, it comes from the MDT .msi and it only picks serviceUI.exe that is very light.
Inside the `.github/workflows/CreateNewRelease.yml I will add something like this:
`
```
      - name: Build project
        run: |
          # Get MDT from Microsoft
          wget https://download.microsoft.com/download/3/3/9/339BE62D-B4B8-4956-B58D-73C4685FC492/MicrosoftDeploymentToolkit_x64.msi
          # Extract MSI
          7z x MicrosoftDeploymentToolkit_x64.msi
          # Copy ServiceUI.exe to Winget-AutoUpdate folder
          mv Modena_File206 Winget-AutoUpdate/ServiceUI.exe
          # Zip WAU
          zip -r WAU.zip Winget-AutoUpdate
          zip WAU.zip Winget-AutoUpdate-Install.ps1
          zip WAU.zip excluded_apps.txt
          zip WAU.zip install.bat
          zip WAU.zip uninstall.bat
          # Zip ADMX
          cd Policies
          zip -r ../WAU_ADMX.zip *
          cd ..
```

**Comment by KnifMelti** [comment]
> I have a plan to onboard it with Github Actions

What a intricate world we live in nowadays... 🤪

**Pull request merged**
