### PR TITLE
-NoNewWindow -Wait so SCCM management is better

### PR DESCRIPTION
**Pull request by KnifMelti**
Better

### CODE REVIEW

**Comment by Romanitho** [comment]
Arf, install.bat is for manual install for me. Not nice user experience to have several windows opened. With sccm, use ps1 directly (or edit bat manually 🤭)
What do you think?

**Comment by KnifMelti** [comment]
With my edits it works as it should; SCCM not showing anything (-NoNewWindow) and the benefit to have the easy arguments handling + a possibility to add something own (in my case a reg value for deployment date) afterwards (-Wait)

**Comment by KnifMelti** [comment]
And it works as a manual install too

**Comment by Romanitho** [comment]
Oh yeah, sorry didn't try. Looks perfect ^^

**Comment by Romanitho** [comment]
Ha wait, I remember why I didn't do that, because `-NoNewWindows -Wait` doesn't work with `-Verb RunAs` ^^

**Comment by Romanitho** [comment]
But at the end, this install.bat is a helper. Anyone can edit it regarding his needs. Once you have yours, reuse it, no ? ^^ I don't know...

**Comment by KnifMelti** [comment]
Ah, OK

**Comment by Romanitho** [comment]
I mean, we need to make a choice between `-NoNewWindows -Wait` and `-Verb RunAs`. And most of admins don't use the install.bat I guess (never use with Intune as I prefer to quickly see my arguments for instance). But in your context, with SCCM you can easily check the Install.bat, so I understand completely your choice ;) And it is shared here for others interested in

**Pull request closed without merging**
