### PR TITLE
Fix network test failing

### PR DESCRIPTION
**Pull request by sagar-m-m**
# Proposed Changes

> Network connection failing when used the provided link on some systems. Changed link in Test-Network.ps1  to repo main page and checked for status code for validation

image

### CODE REVIEW

**Comment by Romanitho** [comment]
Weird that it doesn't work on "some systems".

The proposed solution takes care of captive portal? If you are connected on some guest wifi, it might happen that all URLs points to the captive portal and you get status code 200. So false positive. That's why we check the content of a file.

**Comment by andreasbrett** [comment]
I propose to rather check internet connectivity the Microsoft NCSI way:
https://learn.microsoft.com/en-us/windows-server/networking/ncsi/ncsi-frequently-asked-questions#where-is-the-http-web-probe-server-path-found-in-the-registry

```
try {
    $ncsiHost = Get-ItemPropertyValue -Path "HKLM:\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet" -Name ActiveWebProbeHost
    $ncsiPath = Get-ItemPropertyValue -Path "HKLM:\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet" -Name ActiveWebProbePath
    $ncsiContent = Get-ItemPropertyValue -Path "HKLM:\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet" -Name ActiveWebProbeContent
} catch {
    $ncsiHost = "www.msftconnecttest.com"
    $ncsiPath = "connecttest.txt"
    $ncsiContent = "Microsoft Connect Test"
} finally {
    $ncsiResponse = Invoke-WebRequest -Uri "http://$($ncsiHost)/$($ncsiPath)" -UseBasicParsing
}

if (($ncsiResponse.StatusCode -eq 200) -and ($ncsiResponse.content -eq $ncsiContent)) {
    Write-ToLog "Connected !" "Green"

```

**Comment by Romanitho** [comment]
Go for that one :)

**Comment by Romanitho** [comment]
#476

**Pull request closed without merging**
