### PR TITLE
Add support for wildcard in app ID

### PR DESCRIPTION
**Pull request by Romanitho**
# Proposed Changes

Add support for wildcard in app ids

## Related Issues

> #537 
main idea from @ztrhgf. Thanks ;)

### CODE REVIEW

**Comment by Romanitho** [comment]
@ztrhgf feel free to add any review, that's your piece of work 😊

**Comment by ztrhgf** [comment]
thanks!

**Comment by Romanitho** [comment]
thank you

**Comment by Romanitho** [comment]
Should also fix #548

**Pull request merged**
