### PR TITLE
WTF ?!

### PR DESCRIPTION
**Pull request by Romanitho**

### CODE REVIEW

**Comment by Romanitho** [comment]
@KnifMelti I had to remove the prerelease 1.5.0 due to this...

**Comment by KnifMelti** [comment]
Where thit that come from? 🤔

**Comment by Romanitho** [comment]
Don't even know...

**Comment by KnifMelti** [comment]
7 months ago, you 😉
But, it has worked...

**Comment by Romanitho** [comment]
So weird. It was working so far, but on my WSB it failed to install and I had to fix that.

**Comment by KnifMelti** [comment]
What's a WSB?

**Comment by Romanitho** [comment]
Windows Sandbox :)

**Comment by KnifMelti** [comment]
Must be the French OS then... 😁

**Comment by Romanitho** [comment]
haha, nope. My sandbox is in English. Anyway... it works again. I was surprise to have no complain :D

**Comment by KnifMelti** [comment]
It's been working in my WSB

**Comment by Romanitho** [comment]
not from WiGui in fact

**Comment by KnifMelti** [comment]
Aha, haven't tested GUI since a long time...

**Comment by Romanitho** [comment]
just updating new features

**Pull request merged**
