### PR TITLE
Brand new notif task configuratrion

### PR DESCRIPTION
**Pull request by Romanitho**

### CODE REVIEW

**Comment by Romanitho** [comment]
@KnifMelti working on a brand new notif system to prepare #104 and other kind of options from notifications

**Comment by KnifMelti** [comment]
Looks good and have a lot of potential..

**Comment by Romanitho** [comment]
yes. I wrote that yesterday, it took me a lot of time to understand the thing 😅😅 but yes. For features in the next versions it will be interesting (I hope)

**Comment by Romanitho** [comment]
seems working at this stage 😊

**Comment by KnifMelti** [comment]
Really nice!
Lying in bed with fever and all symptoms of Covid since 3 days...
...cheering on!

**Comment by Romanitho** [comment]
Oh man. Be strong. Hope you'll get better soon.

**Pull request merged**
