### PR TITLE
Get-WAUConfig only if $IsSystem

### PR DESCRIPTION
**Pull request by KnifMelti**
# Proposed Changes
Only if SYSTEM

### CODE REVIEW

**Comment by Romanitho** [comment]
But settings are not applied when running in user context then ?

**Comment by KnifMelti** [comment]
> But settings are not applied when running in user context then ?

Before running in user context the system context has completed and imported all the settings, no need for it when user context runs...

**Comment by KnifMelti** [comment]
Maybe I'm wrong in this new situation (GPO), better to leave it as you wrote it!

**Comment by Romanitho** [comment]
Each time WAU runs, it loads config on the flight from the registry, system or user.
The new GPO system doesn't write any registry key. Only reading from 2 locations with priority to policy location.

**Comment by KnifMelti** [comment]
Yes, I came to that conclusion too.

**Pull request closed without merging**
