### PR TITLE
bug fix for Get-WingetOutdatedApps when handling Chinese characters

### PR DESCRIPTION
**Pull request by guzy0324**
# Proposed Changes

> (Describe the changes and rationale behind them)

## Related Issues

https://github.com/Romanitho/Winget-AutoUpdate/issues/363#issuecomment-1646523644

### CODE REVIEW

**Comment by Romanitho** [comment]
Resolves #363

**Comment by guzy0324** [comment]
https://github.com/Romanitho/Winget-AutoUpdate/issues/363#issuecomment-1649125892

**Comment by guzy0324** [comment]
@Romanitho  I noticed that the [Handle Chinese chars](https://github.com/Romanitho/Winget-AutoUpdate/commit/22a13450ac13f80f3a5ee5f230610e673a18b527) commit is not merged into the main branch. Also, for [lines 61 to 62](https://github.com/Romanitho/Winget-AutoUpdate/blob/Chinese-bug/Winget-AutoUpdate/functions/Get-WingetOutdatedApps.ps1#L61-L62), the length of id and version should not subtract the `$nameDeclination`. Here’s the updated code:

```shell
            $software.Id = $line.Substring($idStart - $nameDeclination, $versionStart - $idStart).TrimEnd()
            $software.Version = $line.Substring($versionStart - $nameDeclination, $availableStart - $versionStart).TrimEnd()
```

**Comment by Romanitho** [comment]
Hi. Thanks for your feedback. Is it possible for you to do all the changes to make it to work correctly as I'm not on my computer at the moment. This way I just merge your new PR.

**Comment by Romanitho** [comment]
Hi,
After some investigations, this PR causing the issue #372 
I guess that Russian characters are similar issue than Chinese one.
the `GetByteCount` part report wrong value.

probably we need to keep our first approach with your change ` -replace '[\u4e00-\u9fa5]', '**'`

**Comment by Romanitho** [comment]
maybe something like this ? 
```
    #Get header titles
    $index = $lines[$fl] -split '\s+'

    # Line $fl has the header, we can find char where we find ID and Version
    $idStart = $lines[$fl].IndexOf($index[1] -replace '[\u4e00-\u9fa5]', '**'))
    $versionStart = $lines[$fl].IndexOf($index[2] -replace '[\u4e00-\u9fa5]', '**'))
    $availableStart = $lines[$fl].IndexOf($index[3] -replace '[\u4e00-\u9fa5]', '**'))
```

**Comment by guzy0324** [comment]
> Hi, After some investigations, this PR causing the issue #372 I guess that Russian characters are similar issue than Chinese one. the `GetByteCount` part report wrong value.
> 
> probably we need to keep our first approach with your change ` -replace '[\u4e00-\u9fa5]', '**'`

I think I have figured out why this happen. Some characters like Russian characters have 2 bytes, but they have the same width with Latin characters. I think change all `System.Text.Encoding]::UTF8.GetByteCount(*)` to `*.Length` will fix this.

**Comment by Romanitho** [comment]
Do you make the change and submit a PR, or do you want me to change it?

**Comment by guzy0324** [comment]
> Do you make the change and submit a PR, or do you want me to change it?

https://github.com/Romanitho/Winget-AutoUpdate/pull/374

**Pull request merged**
