### PR TITLE
Fix runas if install/uninstall bat are not run as admin

### PR DESCRIPTION
**Pull request by Romanitho**

### CODE REVIEW

**Comment by KnifMelti** [comment]
For me, if I include `-NoNewWindow` (but `-Wait` is OK) in the line it doesn't run, do you know why?
`SET PowershellCmd=Start-Process powershell.exe -Verb RunAs -NoNewWindow -Wait -Argument '-noprofile -executionpolicy bypass -file "%~dp0Winget-AutoUpdate-Install.ps1" %arguments%`

**Comment by Romanitho** [comment]
Because -NoNewWindow can only run process in the same context. Bat is run as standard user so it cannot self elevate in admin. That's why -wait works

**Comment by KnifMelti** [comment]
The old way works for us in SCCM environment (keeping it 😉):
```
SET PowershellCmd=Start-Process powershell.exe -NoNewWindow -Wait -Argument '-noprofile -executionpolicy bypass -file "%~dp0Winget-AutoUpdate-Install.ps1" %arguments%
powershell -Command "& {Get-ChildItem -Path '%~dp0' -Recurse | Unblock-File; %PowershellCmd%'}" -Verb RunAs

```

**Comment by Romanitho** [comment]
sure, because it is run in system context ;)

**Pull request merged**
