### PR TITLE
Review system contect notification when ServiceUI is called.

### PR DESCRIPTION
**Pull request by Romanitho**
# Proposed Changes

- Direct call the notification when running with system context through ServiceUI

### CODE REVIEW

**Comment by Romanitho** [comment]
Strange. This change only seems to work in WSB. @KnifMelti could you confirm same behavior? Thanks 😅

**Comment by KnifMelti** [comment]
When I got the time to look into it, yes. Lots of work right now...

**Comment by KnifMelti** [comment]
> could you confirm same behavior?

Confirmed.
It only notif me with a toast when finding upgrades if I run it under WSB...

**Comment by Romanitho** [comment]
weird...

**Pull request merged**
