### PR TITLE
Fix missing settings during MSI update settings migration

### PR DESCRIPTION
**Pull request by Romanitho**

### CODE REVIEW

**Comment by KnifMelti** [comment]
Original **stable 1.21.7** install string: `-Silent -DoNotUpdate -RunOnMetered -InstallUserContext -StartMenuShortcut -ListPath...`
From **stable 1.21.7** to **stable 1.21.12**, then from 1.21.12 to **1.22.1 Preview (MSI)** - now the trigger **At log on** 👌 is gone.

But the **WAU_DoNotRunOnMetered** still gets set to **1**, sorry...

image

**Comment by Romanitho** [comment]
Strange. I ran some tests, and I didn’t notice any problems. I need to test again. But I set the WAU-DoNotRunOnMetered to 1 by default, which should change to 0 if you add -RunOnMetered.
Then, updating to MSI should keep the setting. 🤔

**Comment by Romanitho** [comment]
#722

**Comment by Romanitho** [comment]
thanks again @KnifMelti for your help 👍

**Comment by KnifMelti** [comment]
Now confirmed working! 😍

**Pull request merged**
