### PR TITLE
Revert "Added support for user profile installed apps 🥳"

### PR DESCRIPTION
**Pull request by Romanitho**
Missing parts

### CODE REVIEW

**Comment by KnifMelti** [comment]
I fixed the uninstall and had just 1 shortcut running the "system" task...
...and at my place it did run as expected first system, then user (my user installed apps upgraded via WAU with Notifs
Was there something else that didn't work?

**Comment by KnifMelti** [comment]
Noticed an 1.5 min delay in the log when it created lists, and no log for user apps

**Comment by Romanitho** [comment]
for me, it seems ok. but I need to tidy things up.
for the 40s delay, I think this is due to the `Winget export` command, that can be slow in my opinion, but the export is Json format, to much easier to manage in PS

**Comment by Romanitho** [comment]
and for your user log, I double checked what we've done in the `Start-init` function. You should have your user context log in your user profile.

**Pull request merged**
