### PR TITLE
Ajustements

### PR DESCRIPTION
**Pull request by Romanitho**

### CODE REVIEW

**Comment by Romanitho** [comment]
@KnifMelti What do you think about running notification first?
And ACL changed for re-intall from sources

**Comment by KnifMelti** [comment]
It doesn't matter if you run the task first or the toast; there's an delay in both so they start at the same time...

**Comment by Romanitho** [comment]
very true. I tried to reduce this delay ^^

**Comment by KnifMelti** [comment]
It looks nicer now 😉

**Comment by Romanitho** [comment]
For user run I was thinking about another way to informe them that the manual checking is running. A little windows waiting for the 2 scheduled task (system and user) to end.  a little bit like what we did for WiGui. no delay and close when finished

**Comment by KnifMelti** [comment]
Might work.. ..even if the GUI style then differs...
...could you build in some sort of $OnClickAction = "$WorkingDir\logs\updates.log".
We use it to open the logs from the toast at the same time when we wan't to check the run...

**Comment by Romanitho** [comment]
you have the log shortcut now :p :p

**Comment by KnifMelti** [comment]
I can live with that 😊

**Pull request merged**
