### PR TITLE
Added Notification Level Feature

### LINKED ISSUE #55: Notification Options on Install
Is it possible to have an install parameter that disables/modifies the notify function? I'm very interested in using this, but if even a single application install fails we will have tons of users call our helpdesk to complain.

Alternatively, being able to only show certain notifications (only show successful installs) and hiding others would be great!

### PR DESCRIPTION
**Pull request by Romanitho**
New feature for notification display
Closes #55

### CODE REVIEW

**Comment by Romanitho** [comment]
@KnifMelti I need help maybe 😅
As a good Frenchman, English may probably be better ^^ feel free to correct or add precision on readme. I changed Mods example to a more familiar one.

**Comment by KnifMelti** [comment]
I'll take a look. How long time do I get? ;)

**Comment by Romanitho** [comment]
As long as you need 😋 
just 1.8.0 released. Notification level feature and other customisations will be part of 1.9.0 version. So...

**Comment by KnifMelti** [comment]
Google.Chrome doesn't install a desktop shortcut.

Here's my take:

From version 1.8.0, The Mods feature allows you to run an additional script when upgrading or installing an app.
Just put the script in question with the App ID followed by the "-upgrade" or "-install" suffix in the "mods" folder.   
WAU will call `AppID-upgrade.ps1` and/or `AppID-install.ps1` (if they differs, otherwise the "-install" mod will be used for upgrades too) if it exists in the "mods" folder just after the upgrade/install.
> Example:  
> If you want to run a script that removes the desktop shortcut from "%PUBLIC%\Desktop" (we don't want to fill the desktop with shortcuts our users can't delete) just after installing "Acrobat Reader DC" (32-bit), prepare a powershell script that removes the Public Desktop shortcut "Acrobat Reader DC.lnk" and name your script like this:
> `Adobe.Acrobat.Reader.32-bit-install.ps1` and put it in the "mods" folder.

You can find more information on [Winget-Install](https://github.com/Romanitho/Winget-Install) Repo, as it's a related feature

**Comment by Romanitho** [comment]
Oh, not shortcut for Chrome haha 😅 I haven't tried to install to be honest, it was the first app in my mind.
But as usual, nice job for you piece of doc.

**Comment by Romanitho** [comment]
Done.

**Pull request merged**
