### PR TITLE
Override mods done (+error handling)

### PR DESCRIPTION
**Pull request by KnifMelti**
More choices for everyone...

### CODE REVIEW

**Comment by Nesovj** [comment]
Thank you for implementing my suggestion!

**Comment by KnifMelti** [comment]
Still, even after upgrading like you did (but with an **Adobe.Acrobat.Reader.64-bit-override.txt** mod containing **"/sAll /rs /msi EULA_ACCEPT=YES DISABLEDESKTOPSHORTCUT=1"**) from version **22.002.20212** to **22.003.20258** I still get a shortcut (**Adobe Acrobat.lnk** ???) on the Desktop but the **EULA** is gone...
...could be my machine.

The Adobe install log with all the correct parameters from **WAU** running with an **-override txt** mod:

```
[2022-12-09 03:43:39] Adobe SFX 10.0.0.1 logging started.
[2022-12-09 03:43:39] CommandParam CmdLine: "C:\WINDOWS\TEMP\WinGet\defaultState\Adobe.Acrobat.Reader.64-bit.22.003.20258\AcroRdrDCx642200320258_MUI.exe" /sAll /rs /msi EULA_ACCEPT=YES DISABLEDESKTOPSHORTCUT=1
[2022-12-09 03:43:39] CommandParam passToSetup_  : /sAll /rs /msi EULA_ACCEPT=YES DISABLEDESKTOPSHORTCUT=1
[2022-12-09 03:43:39] CommandParam bSilent_
[2022-12-09 03:43:39] TempFolder: C:\WINDOWS\TEMP\
[2022-12-09 03:43:39] Support folder: C:\ProgramData\Adobe\Temp\10937
[2022-12-09 03:43:39] Extracting: C:\ProgramData\Adobe\Temp\10937\config.bin
[2022-12-09 03:43:39] CheckSystemRequirements os,sp = 62 0 osString = 62W6, physicalMemory (16323) = 16384
[2022-12-09 03:43:39] Adding extracted installer size to the total size: 1118
[2022-12-09 03:43:39] CheckDiskSpace...
[2022-12-09 03:43:39] Required size in MB:  1578
[2022-12-09 03:43:39] Available disk space in MB:  82265
[2022-12-09 03:43:39] IsAlreadyInstalled...
[2022-12-09 03:43:39] SetupInstaller...
[2022-12-09 03:43:39] Extracting: C:\ProgramData\Adobe\Temp\10937\installer.bin
[2022-12-09 03:43:44] Attempted to cleanup folder failed: C:\Program Files\Common Files\Adobe\Acrobat\Setup\{AC76BA86-1033-FF00-7760-BC15014EA700}\RDC
[2022-12-09 03:43:44] Installer folder: C:\Program Files\Common Files\Adobe\Acrobat\Setup\{AC76BA86-1033-FF00-7760-BC15014EA700}\RDC
[2022-12-09 03:43:44] Extracting files from Archive: C:\ProgramData\Adobe\Temp\10937\installer.bin
[2022-12-09 03:44:23] StartInstaller...
[2022-12-09 03:44:23] CreateProcess cmdLine: "C:\Program Files\Common Files\Adobe\Acrobat\Setup\{AC76BA86-1033-FF00-7760-BC15014EA700}\RDC\setup.exe" /sAll /rs /msi EULA_ACCEPT=YES DISABLEDESKTOPSHORTCUT=1 DISABLE_CACHE=1
[2022-12-09 03:45:26] Installer finished with exit code: 0
[2022-12-09 03:45:26] Cleanup...
[2022-12-09 03:45:26] Program finished with exit code: 0

```

**Comment by KnifMelti** [comment]
Thank you @Nesovj for the great idea! 👌

**Comment by Nesovj** [comment]
I bet it is the issue with the latest release: [https://www.adobe.com/devnet-docs/acrobatetk/tools/ReleaseNotesDC/continuous/dccontinuousoct2022qfe.html#bug-fixes](url)

The computer I tested on had Adobe 32 bit originally installed with an .mst transforms file.

I tried on a blank VM and get the desktop shortcut with `--override` only on the latest version of Adobe.Acrobat.Reader.64.

Good thing you already have the `AppID-installed.ps1` mod!
```
#Delete Public Desktop Shortcut
$FileName = "$env:PUBLIC\Desktop\Adobe Acrobat.lnk"

if (Test-Path $FileName) {
  Remove-Item -Path $FileName -Force
}
```

**Comment by Romanitho** [comment]
Wow guys, you're making it better and better... thank you for your hard work 👍

**Comment by KnifMelti** [comment]
We're waiting for you @Romanitho with #228 #235 etc, etc, etc... 😁
...but, you soon have another life to live ❤️❤️❤️

**Comment by KnifMelti** [comment]
Can't get the Errorlevel from Exit 1 over to `User-Run.ps1`, leaving the `$NotifLocale.local.outputs.output[9].message` to `$MessageType = "success"` (giving up)...

**Comment by KnifMelti** [comment]
Working on an old school solution, taking a break now...

**Comment by KnifMelti** [comment]
Now, really done! 😁

**Comment by KnifMelti** [comment]
END.

**Comment by KnifMelti** [comment]
Just like https://github.com/Romanitho/Winget-Install/pull/64#issuecomment-1295810725

**Pull request merged**
