### PR TITLE
Add mods on WAU.msi install

### PR DESCRIPTION
**Pull request by Romanitho**
# Proposed Changes

- Same as included/excluded_app.txt, mods can be placed in the source location:

image

The mods will get copied during installation.

### CODE REVIEW

**Comment by Romanitho** [comment]
@KnifMelti for first install. Don't know if it can help. I was thinking of SCCM or Autopilot scenarios.

**Comment by KnifMelti** [comment]
No -Force in copy?
Good you deletes mods on uninstall!

**Comment by Romanitho** [comment]
We can use "-force" to overwrite. Perhaps it's a good idea.
On upgrade, if you want to push new mods, you're right. I'll take a closer look at that. 😅

**Comment by Romanitho** [comment]
I made new tests on my WSB:

1.
- Installed msi 1.21.1
- put custom mods in Mods WAU's location
- enabled prerelease in regedit
- run WAU
- Custom mods still there after upgrade to 1.22.2-n ✅
2.
- Installed msi 1.21.1
- put custom mods in Mods WAU's location
- installed msi 1.22.2-n manually
- Custom mods still there after upgrade ✅
3.
- Installed msi 1.21.1
- put custom mods in Mods WAU's location
- installed msi 1.22.2-n with Mods in root msi location
- Custom mods still there after upgrade and the ones in 1.22.2-n replaced the 1.21.1 ones ✅
4.
- Uninstalled 1.22.2-n
- Everything removed ✅

**Comment by KnifMelti** [comment]
Im running Proxmox with a full Win11 as major test machine with rollback to snapshot afterwards, WSB for fast testing.
I'm in bed sick now so I'm not testing this 😉

**Comment by KnifMelti** [comment]
GitHub Copilot says:

The selected line in the code is:
```powershell
Copy-Item -Path $ModsFolder -Destination "$InstallPath" -Recurse
```

Even though the `-Force` parameter is not explicitly used, the destination can still be overwritten because of how `Copy-Item` operates in PowerShell. By default, `Copy-Item` will overwrite existing files in the destination if they have the same name as the source files. The `-Recurse` parameter ensures that all items and child items in the source directory are copied to the destination, which includes overwriting files if they already exist in the destination directory.

**Comment by Romanitho** [comment]
so, that's perfect, no? :p

**Pull request merged**
