### PR TITLE
[Bug]: PowerShell Core Incompatibility #379 [Feature Request]: Winget…

### PR DESCRIPTION
**Pull request by KnifMelti**
Update to Winget v1.5.2201

# Proposed Changes

Fixes WSB and Powershell Core compatibility

## Related Issues

#379 #381 #384

### CODE REVIEW

**Comment by KnifMelti** [comment]
...or, is this a better option (from `Winget-Install-GUI.ps1`):
```
# import Appx module if the powershell version is 7/core
if ( $psversionTable.PSEdition -eq "core" ) {
    import-Module -name Appx -UseWIndowsPowershell -WarningAction:SilentlyContinue
}

```

**Comment by KnifMelti** [comment]
Add-AppxPackage "$PSScriptRoot\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle" fails under SYSTEM!
```
Deployment Add operation rejected on package Microsoft.DesktopAppInstaller_2023.808.2243.0_neutral_~_8wekyb3d8bbwe from
: Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle install request because the Local System account is not allowe
d to perform this operation.
```

**Comment by KnifMelti** [comment]
Closing...

**Comment by Romanitho** [comment]
Should be. If this is the case, readme will be updated.

**Pull request closed without merging**
