### PR TITLE
ServiceUI added to handle some apps

### PR DESCRIPTION
**Pull request by Romanitho**
# Proposed Changes

- Added ServiceUI to handle some apps that need user connected (Like paint.net)

### CODE REVIEW

**Comment by KnifMelti** [comment]
I.ve had problems with **dnGrep.dnGrep**, tested now with this and it just installed!

**Comment by KnifMelti** [comment]
It updated correctly, but now it thinks it should be installed every time (black listing it again):
```
-> Available update : dnGrep 3.2.306 (x64). Current version : 3.2.306.0. Available version : 4.0.129.0.
-> Available update : Microsoft .NET Core Runtime - 2.1.30 (x64). Current version : < 3.1.25. Available version : 3.1.32.
-> Available update : Microsoft Visual C++ 2015-2022 Redistributable (x64) -. Current version : 14.36.32532.0. Available version : 14.38.32919.0.
-> Available update : Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.. Current version : 12.0.30501.0. Available version : 12.0.40664.0.
-> Available update : Microsoft .NET SDK 6.0.415 (x64). Current version : > 3.1.426. Available version : 6.0.415.
-> Available update : Microsoft Visual C++ 2015-2022 Redistributable (x86) -. Current version : 14.36.32532.0. Available version : 14.38.32919.0.
-> Available update : UltraEdit. Current version : 30.1.0.23. Available version : 30.1.23.
05:11:31 - Microsoft Visual C++ 2013 Redistributable (x86) - 12.0. : Skipped upgrade because it is in the excluded app list
05:11:32 - Updating dnGrep 3.2.306 (x64) from 3.2.306.0 to 4.0.129.0...
05:11:36 - ##########   WINGET UPGRADE PROCESS STARTS FOR APPLICATION ID 'dnGrep.dnGrep'   ##########
05:11:36 - -> Running: Winget upgrade --id dnGrep.dnGrep --accept-package-agreements --accept-source-agreements -h


  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 8.19 MB
  ███████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 8.19 MB
  ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 8.19 MB
  ██████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 8.19 MB
  ██████████████████▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 8.19 MB
  █████████████████████▒▒▒▒▒▒▒▒▒  6.00 MB / 8.19 MB
  █████████████████████████▒▒▒▒▒  7.00 MB / 8.19 MB
  █████████████████████████████▒  8.00 MB / 8.19 MB
  ██████████████████████████████  8.19 MB / 8.19 MB

No installed package found matching input criteria.
05:12:17 - ##########   WINGET UPGRADE PROCESS FINISHED FOR APPLICATION ID 'dnGrep.dnGrep'   ##########
05:12:17 - dnGrep 3.2.306 (x64) updated to 4.0.129.0 !

```

**Comment by KnifMelti** [comment]
Ah, it was due to an old registry uninstall entry, now manually deleted!
✌️

**Comment by Romanitho** [comment]
Ahah. WAU becomes better and better 🤪

**Comment by Romanitho** [comment]
The next release will be 1.18.0
Huge changes. Still need to be tested to be set as stable

**Comment by Romanitho** [comment]
Now that ServiceUI is implemented, we could add an option to the upgrade/install behavior. Currently, the `-h` hide the Upgrade/installation. We could take advantage of the command without the `-h` if needed. This way, we can have a progress bar from the installer itself (if supported), like so:
image
`-ShowUpgrades` could be a new WAU option for new install and integrated to GPO.

**Comment by KnifMelti** [comment]
Sounds good to have.

**Comment by KnifMelti** [comment]
...but maybe a security challenge if the app then runs in in full graphic mode and presents a file browser or a help link...

**Comment by Romanitho** [comment]
That's very true.
But for personal installations maybe...
will not implement for now

**Comment by KnifMelti** [comment]
Why not if it is a manageable setting?
Could be useful for home users, but it needs to beadapted to the `-NotificationLevel` too!

**Comment by Romanitho** [comment]
Yes, manageable by GPO 😅
The notification level need to be Full of course. Except if you want to display the progress bar without any notif, or only success 🤷🏼‍♂️

**Pull request merged**
