### PR TITLE
Gpo enhancement / reworked

### PR DESCRIPTION
**Pull request by Romanitho**
# Proposed Changes

- Full GPO rewrite
- Dedicated Scheduled task
- Generate and add ADMX in assets

## Related Issues

> #346

### CODE REVIEW

**Comment by Romanitho** [comment]
#256

**Comment by KnifMelti** [comment]
**WAU!** You really did it... 💕
...my big lump in the stomach is gone!
Really, really simplified and handleable!!!!!

FallingDownGIF

**Comment by Romanitho** [comment]
It was not that easy to have something that works as expected.
Will remain in pre version for now waiting for bug discovery 😅

**Comment by KnifMelti** [comment]
I think I found 1... #421

**Comment by Romanitho** [comment]
I'll check that tomorrow morning 👌🏼
Thanks

**Comment by KnifMelti** [comment]
This is.. ..Perfect! 👍🤪

**Pull request merged**
