### PR TITLE
re-run install if 32bit process on 64bit OS

### PR DESCRIPTION
**Pull request by Romanitho**

### CODE REVIEW

**Comment by Romanitho** [comment]
@KnifMelti to avoid workaround sysnative thing.

**Comment by KnifMelti** [comment]
Ah, really nice!
Then, I guess, you've had an exchange with @jhochwald about **ARM64** (or did you Altavista that 😂)

**Comment by Romanitho** [comment]
haha, no. This is a piece of code I had in my library ^^ and it takes care about ARM64 😉
I will apply it to Winget-Install repo as well.

So we will continue to advise community to use sysnative in the Intune install command, but from now it will work even without it.

**Comment by jhochwald** [comment]
That is a nice addition.
I use this snippet in mostly all Intune related code:

```PowerShell
#region ARM64Handling
# Restart Process using PowerShell 64-bit
if ($ENV:PROCESSOR_ARCHITEW6432 -eq 'AMD64')
{
   try
   {
      &"$ENV:WINDIR\SysNative\WindowsPowershell\v1.0\PowerShell.exe" -File $PSCOMMANDPATH
   }
   catch
   {
      Throw ('Failed to start {0}' -f $PSCOMMANDPATH)
   }

   exit
}
#endregion ARM64Handling
```

**Comment by Romanitho** [comment]
yes, but in your snippet I think `-File $PSCOMMANDPATH` doesn't take care about the script arguments... That's why I use `-Command $($MyInvocation.line)`.

**Comment by jhochwald** [comment]
Correct! My Snippet is used within Intune, where NO arguments are used. Mostly for Check/Remediation scripts, what I use a lot.
The Intune process itself is (still) 32Bit, therefore sometime the script is started as 32Bit :(
But I will steal your sippet if I have the need for cmdlets or scripts where arguments can happen ;-)

**Pull request merged**
