### PR TITLE
[DRAFT] Improved user notification

### PR DESCRIPTION
**Pull request by Romanitho**

### CODE REVIEW

**Comment by Romanitho** [comment]
@KnifMelti another approach for user run (and if people prefect to get warned before updating, we just need to schedule the `user-run.ps1`)

**Comment by KnifMelti** [comment]
Yes, I saw the $WAUClass - Nice!

**Comment by Romanitho** [comment]
still a lot of work to do, but it's going forward

**Comment by dimzen** [comment]
Is there an update on this topic? Sounds like a great functionality to me!

**Comment by Romanitho** [comment]
yes, was very busy. But I will continue to work on this

**Comment by Romanitho** [comment]
a new PR will be created soon from this branch:
https://github.com/Romanitho/Winget-AutoUpdate/tree/user-approval

**Pull request closed without merging**
