### PR TITLE
-AllUsers for Get-AppxPackage

### PR DESCRIPTION
**Pull request by KnifMelti**
# Proposed Changes
A small fix based on Winget-Install

### CODE REVIEW

**Comment by KnifMelti** [comment]
Linter **kics** kicked in?

```
❌ Linted [REPOSITORY] files with [kics]: Found 1 error(s) - (39.07s) (expand for details)
  - Using [kics v1.7.10] https://megalinter.io/7.5.0/descriptors/repository_kics
  - MegaLinter key: [REPOSITORY_KICS]
  - Rules config: identified by [kics]
  --Error detail:
  
                     .0MO.                                    
                     OMMMx                                    
                     ;NMX;                                    
                      ...           ...              ....     
  WMMMd     cWMMM0.  KMMMO      ;xKWMMMMNOc.     ,xXMMMMMWXkc.
  WMMMd   .0MMMN:    KMMMO    :XMMMMMMMMMMMWl   xMMMMMWMMMMMMl
  WMMMd  lWMMMO.     KMMMO   xMMMMKc...'lXMk   ,MMMMx   .;dXx 
  WMMMd.0MMMX;       KMMMO  cMMMMd        '    'MMMMNl'       
  WMMMNWMMMMl        KMMMO  0MMMN               oMMMMMMMXkl.  
  WMMMMMMMMMMo       KMMMO  0MMMX                .ckKWMMMMMM0.
  WMMMMWokMMMMk      KMMMO  oMMMMc              .     .:OMMMM0
  WMMMK.  dMMMM0.    KMMMO   KMMMMx'    ,kNc   :WOc.    .NMMMX
  WMMMd    cWMMMX.   KMMMO    kMMMMMWXNMMMMMd .WMMMMWKO0NMMMMl
  WMMMd     ,NMMMN,  KMMMO     'xNMMMMMMMNx,   .l0WMMMMMMMWk, 
  xkkk:      ,kkkkx  okkkl        ;xKXKx;          ;dOKKkc    
  
  
  Scanning with Keeping Infrastructure as Code Secure v1.7.10
  
  
  
  Files scanned: 9
  Parsed files: 9
  Queries loaded: 296
  Queries failed to execute: 0
  
  ------------------------------------
  
  Unpinned Actions Full Length Commit SHA, Severity: MEDIUM, Results: 11
  Description: Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload. When selecting a SHA, you should verify it is from the action's repository and not a repository fork.
  Platform: CICD
  Learn more about this vulnerability: https://docs.kics.io/latest/queries/cicd-queries/555ab8f9-2001-455e-a077-f2d0f41e2fb9
  
  	[1]: .github/workflows/mega-linter.yml:93
  
  		092:         if: steps.ml.outputs.has_updated_sources == 1 && (env.APPLY_FIXES_EVENT == 'all' || env.APPLY_FIXES_EVENT == github.event_name) && env.APPLY_FIXES_MODE == 'commit' && github.ref != 'refs/heads/main' && (github.event_name == 'push' || github.event.
  		093:         uses: stefanzweifel/git-auto-commit-action@v5
  		094:         with:
  
  
  	[2]: .github/workflows/WAU-AutoCreatePreVersion.yml:56
  
  		055:       - name: Auto Increment Semver Action
  		056:         uses: MCKanpolat/auto-semver-action@1.0.10
  		057:         id: versioning
  
  
  	[3]: .github/workflows/WAU-CreateNewVersion.yml:42
  
  		041:       - name: Overwrite Version.txt file
  		042:         uses: DamianReeves/write-file-action@v1.2
  		043:         with:
  
  
  	[4]: .github/workflows/WAU-CreateNewVersion.yml:76
  
  		075:       - name: Create release
  		076:         uses: "ncipollo/release-action@v1"
  		077:         with:
  
  
  	[5]: .github/workflows/mega-linter.yml:47
  
  		046:         # More info at https://megalinter.github.io/flavors/
  		047:         uses: oxsecurity/megalinter@v7
  		048:         env:
  
  
  	[6]: .github/workflows/WAU-AutoCreatePreVersion.yml:69
  
  		068:       - name: Overwrite Version.txt file
  		069:         uses: DamianReeves/write-file-action@v1.2
  		070:         with:
  
  
  	[7]: .github/workflows/WAU-AutoCreatePreVersion.yml:76
  
  		075:       - name: Commit & Push
  		076:         uses: actions-js/push@v1.4
  		077:         with:
  
  
  	[8]: .github/workflows/WAU-AutoCreatePreVersion.yml:103
  
  		102:       - name: Create release
  		103:         uses: "ncipollo/release-action@v1"
  		104:         id: release
  
  
  	[9]: .github/workflows/WAU-CreateNewVersion.yml:34
  
  		033:       - name: Auto Increment Semver Action
  		034:         uses: MCKanpolat/auto-semver-action@1.0.10
  		035:         id: versioning
  
  
  	[10]: .github/workflows/WAU-CreateNewVersion.yml:49
  
  		048:       - name: Commit & Push
  		049:         uses: actions-js/push@v1.4
  		050:         with:
  
  
  	[11]: .github/workflows/mega-linter.yml:74
  
  		073:         if: steps.ml.outputs.has_updated_sources == 1 && (env.APPLY_FIXES_EVENT == 'all' || env.APPLY_FIXES_EVENT == github.event_name) && env.APPLY_FIXES_MODE == 'pull_request' && (github.event_name == 'push' || github.event.pull_request.head.repo.full_n
  		074:         uses: peter-evans/create-pull-request@v5
  		075:         with:
  
  
  
  Results Summary:
  HIGH: 0
  MEDIUM: 11
  LOW: 0
  INFO: 0
  TOTAL: 11

```

**Comment by Romanitho** [comment]
I don't know

**Comment by KnifMelti** [comment]
Can it be the name, I could try close it and then try again with an other name...

**Comment by Romanitho** [comment]
it is related to the github actions. I will try to secure that with github best practices

**Comment by KnifMelti** [comment]
So I don't have to do anything

**Comment by Romanitho** [comment]
not for now ^^

**Comment by Romanitho** [comment]
Ok, I pull my PR and you should be good to go ;)

**Pull request merged**
