### PR TITLE
Better Functions

### PR DESCRIPTION
**Pull request by KnifMelti**
# Proposed Changes
`Update-Winget` as an external Function, `Get-StoreApps` changed to `Update-StoreApps`
`Winget-Autoupdate-Install` and `Invoke-PostUpdateActions` now using `Update-Winget`

### CODE REVIEW

**Comment by KnifMelti** [comment]
Example of **_WAU-mods.ps1**:
```
<# #Mods for WAU (if Network is active/any WinGet is installed/running as SYSTEM)
Winget-Upgrade.ps1 calls this script with the code:
[Write-ToLog "Running Mods for WAU..." "Yellow"
& "$Mods\_WAU-mods.ps1"]
Make sure your Functions have unique names!
Exit 1 to Re-run WAU from this script!
#>

<# FUNCTIONS #>



<# ARRAYS/VARIABLES #>

$WinGetAvailableVersion = Get-WinGetAvailableVersion
$WinGetInstalledVersion = & $Winget --version
$WinGetInstalledVersion = $WinGetInstalledVersion.Replace("v", "")

<# MAIN #>

#Check for GPO changes
$PoliciesTask = Get-ScheduledTask -TaskName 'Winget-AutoUpdate-Policies' -ErrorAction SilentlyContinue
if ($PoliciesTask) {
    $null = $PoliciesTask | Start-ScheduledTask -ErrorAction SilentlyContinue
    Write-ToLog "-> Evaluating GPO settings" "Yellow"
}

#Exclude -preview versions
If (!($WinGetAvailableVersion -match "-pre") -and ($WinGetAvailableVersion -gt $WinGetInstalledVersion)) {
    Write-ToLog "-> WinGet is not up to date (v$WinGetInstalledVersion) - v$WinGetAvailableVersion is available:" "Red"
    Update-WinGet $WinGetAvailableVersion $($WAUConfig.InstallLocation) $true
    Update-StoreApps $true

    #Exit and Re-run WAU
    Exit 1
}

if ($PoliciesTask) {
    Write-ToLog "...all done!" "Green"
} else {
    Write-ToLog "...everything's already been done!" "Green"
}

Exit 0

```

**Comment by Romanitho** [comment]
seems really good. Nice rework.

**Comment by Romanitho** [comment]
MegaLinter spotted other thing to optimise 😅
```

Processing linters on [2] parallel cores…
✅ Linted [COPYPASTE] files with [jscpd]: Found 9 non blocking error(s) - (2.63s) (expand for details)
  - Using [jscpd v3.5.9] https://megalinter.io/7.3.0/descriptors/copypaste_jscpd
  - MegaLinter key: [COPYPASTE_JSCPD]
  - Rules config: [.jscpd.json]
  --Error detail:
  Clone found (powershell):
   - Winget-AutoUpdate/mods/_Mods-Functions.ps1 [109:13 - [116](https://github.com/Romanitho/Winget-AutoUpdate/actions/runs/6516589851/job/17700259244#step:4:119):19] (7 lines, 99 tokens)
     Winget-AutoUpdate/mods/_Mods-Functions.ps1 [53:9 - 60:19]
  
  Clone found (powershell):
   - Winget-AutoUpdate/mods/_Mods-Functions.ps1 [[117](https://github.com/Romanitho/Winget-AutoUpdate/actions/runs/6516589851/job/17700259244#step:4:120):25 - 129:59] (12 lines, [128](https://github.com/Romanitho/Winget-AutoUpdate/actions/runs/6516589851/job/17700259244#step:4:131) tokens)
     Winget-AutoUpdate/mods/_Mods-Functions.ps1 [61:21 - 73:59]
  
  Clone found (powershell):
   - Winget-AutoUpdate/functions/Start-Init.ps1 [38:9 - 49:91] (11 lines, 117 tokens)
     Winget-AutoUpdate/functions/Start-Init.ps1 [27:9 - 37:7]
  
  Clone found (powershell):
   - Winget-AutoUpdate/functions/Invoke-LogRotation.ps1 [40:21 - 50:6] (10 lines, 116 tokens)
     Winget-AutoUpdate/functions/Start-Init.ps1 [27:9 - 37:7]
  
  Clone found (powershell):
   - Winget-AutoUpdate/functions/Get-WingetOutdatedApps.ps1 [45:2 - 54:2] (9 lines, 102 tokens)
     Winget-AutoUpdate/functions/Get-WingetOutdatedApps.ps1 [29:2 - 39:50]
  
  Clone found (powershell):
   - Winget-AutoUpdate/Winget-Upgrade.ps1 [276:2 - 285:59] (9 lines, 93 tokens)
     Winget-AutoUpdate/Winget-Upgrade.ps1 [259:2 - 268:63]
  
  Clone found (powershell):
   - Winget-AutoUpdate-Install.ps1 [300:2 - 310:2] (10 lines, 110 tokens)
     Winget-AutoUpdate-Install.ps1 [290:9 - 300:7]
  
  Clone found (powershell):
   - Winget-AutoUpdate-Install.ps1 [516:13 - 528:2] (12 lines, 193 tokens)
     Winget-AutoUpdate/WAU-Uninstall.ps1 [45:9 - 56:10]
  
  Clone found (powershell):
   - Winget-AutoUpdate-Install.ps1 [587:1 - 595:2] (8 lines, 101 tokens)
     Winget-AutoUpdate/functions/Add-Shortcut.ps1 [2:1 - 10:2]
```

The `Add-Shortcut` can also be added to `Winget-AutoUpdate-Install.ps1` I guess.

**Comment by KnifMelti** [comment]
Don't know what clone found means.. ..and yes add-shortcut can also be imported

**Comment by Romanitho** [comment]
I guess it means duplicate parts in between files.

**Comment by KnifMelti** [comment]
Let it hav its own life 😁

**Pull request merged**
