### PR TITLE
WAU with mods enabled

### PR DESCRIPTION
**Pull request by KnifMelti**
Have tested a lot, it seems all good and nothing broken as far as I can tell.
Some mistakes were reverted.

### CODE REVIEW

**Comment by KnifMelti** [comment]
@Romanitho  User "**GAJ-san**" is "**KnifMelti@Work**"  :=)

**Comment by Romanitho** [comment]
maybe few optimisations ? :p

```
function Test-Mods ($app){

    $Mods = "$WorkingDir\mods"
    if (Test-Path "$Mods\$app-*"){
        if (Test-Path "$Mods\$app-install.ps1"){
            $ModsInstall = "$Mods\$app-install.ps1"
            $ModsUpgrade = "$Mods\$app-install.ps1"
        }
        if (Test-Path "$Mods\$app-upgrade.ps1"){
            $ModsUpgrade = "$Mods\$app-upgrade.ps1"
        }
        return $ModsInstall,$ModsUpgrade
    }
    else {
        #Takes care of a null situation
        $ModsInstall = $null
        $ModsUpgrade = $null
        return $ModsInstall,$ModsUpgrade
    }

}
```
and then 
```
$ModsInstall, $ModsUpgrade = Test-Mods $($app.Id)
if ($ModsUpgrade){
    Write-Log "Modifications for $($app.Id) during upgrade are being applied..." "Yellow"
    & "$ModsUpgrade"
}
```

**Comment by KnifMelti** [comment]
Ah, you can do that...
...if it works then of course!
It was the $ModsTest.split() that caused a problem if $null

**Comment by Romanitho** [comment]
Yes. In this way we don't  have to handle the split

**Comment by Romanitho** [comment]
`In PowerShell, as in other programming languages, functions define the scope of variables. The values of variables defined within a function block are not available outside the function. However, to avoid undesirable side effects, you should not use the same name for local and global variables.` [source](https://4sysops.com/archives/the-powershell-function-parameters-data-types-return-values/#:~:text=In%20PowerShell%2C%20as%20in%20other,for%20local%20and%20global%20variables.)
So, just to be sure, we could change the name of variables inside the function, but each time you call the function, the variables are "reset".
that's why when I want to reuse a variable outside of a function, I declare the scope: `$Script:Variable` for instance

**Comment by KnifMelti** [comment]
Then, if variables are reset each time a function is called there's no issue at all.

Another thing; in this I modified (then deleted the modifications) in Update-WAU.ps1 and Winget-AutoUpdate-Install.ps1 (the mods directory).
I should have **Undone** the Commits, but I reverted (edited) them back to original instead...
...I can't find a way to Undo what I did, so now I guess my layman way of working in GitHub is going to overwrite your description of the file **Winget-AutoUpdate-Install.ps1**; "_Using preview version to resolve issue as system_" if this Pull request is merged...
...sorry!

**Comment by Romanitho** [comment]
@KnifMelti quick question. If you want to run a script with your Mods feature, but don't want to copy it in the WAU Mods folder. Is it possible ? Let's imagine an app you want to install with specific config that you apply with your mods, but then, not necessary to run it on each new version.

**Comment by KnifMelti** [comment]
You mean in the winget install...
...well, one could check if there's a install-one or something then run that in the winget install and exclude it in copying.
The WAU mods only runs if it's called - install or -upgrade

**Comment by KnifMelti** [comment]
I haven't tested it yet, but it feels/looks right ;)

**Comment by Romanitho** [comment]
I like the idea :)
dont hesitate to PR if you implemented it :)

**Pull request merged**
