### PR TITLE
Added ES .xml translation

### PR DESCRIPTION
**Pull request by JMoreno97**
I have created the xml for Spanish and tested on my computer. It seems working well

### CODE REVIEW

**Comment by Romanitho** [comment]
thanks :)

**Comment by Romanitho** [comment]
Hi. We've updated xml files with new notifications. Could you translate please? 😇

**Comment by JMoreno97** [comment]
> Hi. We've updated xml files with new notifications. Could you translate please? 😇

Yes I will do it as soon as possible.

**Comment by Romanitho** [comment]
Thank you ;)

**Pull request merged**
