### PR TITLE
Symlink install.log to Intune Log folder

### PR DESCRIPTION
**Pull request by FaserF**
# Proposed Changes

Currently only the WAU update log is being symlinked to the Intune folder. I would prefer to symlink the full WAU log folder, so that install/uninstall Logs from winget-install.ps1 are available through Intune too.

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by KnifMelti** [comment]
Does Intune Management Extension collection of log files support sub folders?

**Comment by FaserF** [comment]
Intended to do it by myself with this PR, but yes you are right. I have just tested it with my client and it only contains files, no folders which is sad. The new commit switched this to include the install.log too instead of the full folder which doesnt work.

Thank you for the hint.

**Comment by Romanitho** [comment]
Thanks you guys for your great help :)

**Comment by KnifMelti** [comment]
Sorry, but...
**install.log** only exist if **Winget-Install** is used, but `-ErrorAction SilentlyContinue` takes care of that error.
But, how about **README.md**, **Invoke-PostUpdateActions.ps1**, **Winget-AutoUpdate-Install.ps1** (Uninstall-WingetAutoUpdate) and **WAU-Uninstall.ps1** (I've forgotten about that one too)?

**Comment by Romanitho** [comment]
> Sorry, but... **install.log** only exist if **Winget-Install** is used, but `-ErrorAction SilentlyContinue` takes care of that error. But, how about **README.md**, **Invoke-PostUpdateActions.ps1**, **Winget-AutoUpdate-Install.ps1** (Uninstall-WingetAutoUpdate) and **WAU-Uninstall.ps1** (I've forgotten about that one too)?

Not sure to understand   


> And, I think $WorkingDir\logs\install.log is only correct in the upgrade, not in the install.

I agree. Maybe this should be set from winget-install project itself

**Pull request merged**
